
<!--PAGE CONTENT -->
<div id="content">

	<div class="inner">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header"><?php echo _('Catalogo de Usuarios')?></h1>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<!-- _() es un alias del gettext() -->
                           	<?php echo _('Alta de usuarios')?> 
                        </div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-6">
								<!-- <form role="form" action="<?php echo BASE_URL?>usuario/recepcionUsuario" method="POST" id="form_addusuario"> -->
								<form role="form" method="POST" id="form_addusuario">
									<div class="form-group">
										<label><?php echo _('Usuario')?></label> 
										<input class="form-control" placeholder="Ingrese Usuario" name="usuario" id="usuario">
									</div>
									<div class="form-group">
										<label><?php echo _('Nombre')?></label> 
										<input class="form-control" placeholder="Ingrese Nombre" name="nombre" id="nombre">
									</div>
									<div class="form-group">
										<label><?php echo _('Email')?></label> 
										<input class="form-control" placeholder="Ingrese Email" name="email" id="email">
									</div>
									<div class="form-group">
										<label><?php echo _('Clave')?></label> 
										<input class="form-control" placeholder="Ingrese Clave" name="clave1" id="clave1">
									</div>
									<div class="form-group">
										<label><?php echo _('Repetir Clave')?></label> 
										<input class="form-control" placeholder="Repita Clave" name="clave2" id="clave2">
									</div>
									<div class="form-group">
										<label><?php echo _('Rol')?></label> 
										<select name="rol" id="rol" class="form-control">
											<option value="administrador"><?php echo _('Administrador')?></option>
											<option value="supervisor"><?php echo _('Supervisor')?></option>
											<option value="usuario"><?php echo _('Usuario')?></option>
										</select>
									</div>
									<button type="button" id="btn_registrar" class="btn btn-primary"><?php echo _('Registrar')?></button>
									<button type="button" id="btn_cerrar" class="btn btn-primary"><?php echo _('Cerrar')?></button>
									
<!-- 									submit y reset estan programados -->
<!-- 									mientras que el button no -->

									<div id="zona_respuesta"></div>
								</form>
								
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>
<!--END PAGE CONTENT -->
