<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">

            <div class="row">

                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <a href="<?php echo BASE_URL?>usuario/addusuario">Nuevo</a>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover"
                                       id="dataTables-usuarios">
                                    <thead>
                                    <tr>
                                        <th><?php echo _('Codigo')?></th>
                                        <th><?php echo _('Nombre del Juego')?></th>
                                        <th><?php echo _('email')?></th>
                                        <th><?php echo _('rol')?></th>
                                        <th><?php echo _('fechareg')?></th>
                                        <th><?php echo _('Foto')?></th>
                                        <th><?php echo _('Opciones')?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="body_usuarios">

                                    <?php while($reg = $this->juego->fetch_object()):?>

                                        <tr>
                                            <td><?php echo $reg->id?></td>
                                            <td><?php echo $reg->name?></td>
                                            <td><?php echo $reg->email?></td>
                                            <td><?php echo $reg->rol?></td>
                                            <td><?php echo $reg->fechareg?></td>
                                            <td>
                                                <img height="100px" src="<?php echo BASE_URL?>usuario/getFoto/<?php echo $reg->idusuario?>"/>
                                            </td>
                                            <td><a
                                                        href="<?php echo BASE_URL?>usuario/editUsuario/<?php echo $reg->idusuario?>"><?php echo _('Editar') ?></a>
                                                <a
                                                        href="<?php echo BASE_URL?>usuario/delUsuario/<?php echo $reg->idusuario?>"><?php echo _('Eliminar') ?></a>
                                            </td>
                                        </tr>

                                    <?php endwhile?>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <!-- end row -->


        </div> <!-- container -->

    </div> <!-- content -->

    <footer class="footer text-right">
        2016 - 2017 © Adminto.
    </footer>

</div>


<!-- ============================================================== -->
<!-- End Right content here -->
<!-- ============================================================== -->


