
<!--PAGE CONTENT -->
<div id="content">

	<div class="inner">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header"><?php echo _('Catalogo de Usuarios')?></h1>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<!-- _() es un alias del gettext() -->
                           	<?php echo _('Editar  usuarios')?> 
                        </div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-6">
                                 <!-- <form class="form-signin" action="<?php echo BASE_URL?>producto/editar" method="POST"> -->
                                 <form role="form" method="POST" id="form_editproducto" enctype="multipart/form-data">
                                	<input type="hidden" name="MAX_FILE_SIZE" value="3000000" />
									<div class="form-group">
										<label><?php echo _('Product Code')?></label> <input
											class="form-control"
											name="productCode" id="productCode" value="<?php echo $this->producto->productCode?>" readonly>
									</div>
									<div class="form-group">
										<label><?php echo _('Product Name')?></label> <input
											class="form-control"
											name="productName" id="productName" value="<?php echo $this->producto->productName?>">
									</div>
									<div class="form-group">
										<label><?php echo _('Product Line')?></label> <input
											class="form-control" name="productLine"
											id="productLine" name="" value="<?php echo $this->producto->productLine?>">
									</div>
									<div class="form-group">
										<label><?php echo _('Product Sale')?></label> <input
											class="form-control" name="productScale"
											id="productScale" value="<?php echo $this->producto->productScale?>">
									</div>
									<div class="form-group">
										<label><?php echo _('Product Vendor')?></label> <input
											class="form-control" name="productVendor"
											id="productVendor" value="<?php echo $this->producto->productVendor?>">
									</div>
									<div class="form-group">
										<label><?php echo _('Product Description')?></label> <input
											class="form-control" name="productDescription"
											id="productDescription" value="<?php echo $this->producto->productDescription?>">
									</div>
									<div class="form-group">
										<label><?php echo _('Stock')?></label> <input
											class="form-control" name="quantityInStock"
											id="quantityInStock" value="<?php echo $this->producto->quantityInStock?>">
									</div>
								<div class="form-group">
										<label><?php echo _('Price')?></label> <input
											class="form-control" name="buyPrice"
											id="buyPrice" value="<?php echo $this->producto->buyPrice?>">
									</div>
							<div class="form-group">
										<label><?php echo _('MSRP')?></label> <input
											class="form-control" name="MSRP"
											id="MSRP" value="<?php echo $this->producto->MSRP?>">
									</div>
									<div class="form-group">
										<label><?php echo _('Subir Foto')?></label> 
										<input type="file" class="form-control" name="foto" id="foto">
									</div>
									
									<button type="submit" id="btn_edit"
										class="btn btn-primary"><?php echo _('Actualizar')?></button>
								
									<!-- 									submit y reset estan programados -->
									<!-- 									mientras que el button no -->

									<div id="zona_respuesta"></div>
								</form>

							</div>

						</div>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>
<!--END PAGE CONTENT -->
