<!--PAGE CONTENT -->
<div id="content">

	<div class="inner">
		<div class="row">
			<div class="col-lg-12">

				<h2> <?php echo _('Tabla de Productos')?> </h2>

			</div>
		</div>

		<hr />


		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						
					</div>
					<div class="panel-body">
						<div class="table-responsive">
							<table class="table table-striped table-bordered table-hover"
								id="dataTables-productos">
								<thead>
									<tr>
										<th><?php echo _('Product Code')?></th>
										<th><?php echo _('Product Name')?></th>
										<th><?php echo _('Product Line')?></th>
										<th><?php echo _('Product Sale')?></th>
										<th><?php echo _('Product Vendor')?></th>
										<th><?php echo _('Product Description')?></th>
										<th><?php echo _('Stock')?></th>
										<th><?php echo _('Price')?></th>
										<th><?php echo _('MSRP')?></th>
										<th><?php echo _('Acciones')?></th>
										<th><?php echo _('Foto')?></th>
									</tr>
								</thead>
								<tbody id="body_usuarios">
								
									<?php while($reg = $this->productos->fetch_object()):?>
									
										<tr>
										<td><?php echo $reg->productCode?></td>
										<td><?php echo $reg->productName?></td>
										<td><?php echo $reg->productLine?></td>
										<td><?php echo $reg->productScale?></td>
										<td><?php echo $reg->productVendor?></td>
										<td><?php echo $reg->productDescription?></td>
										<td><?php echo $reg->quantityInStock?></td>
										<td><?php echo $reg->buyPrice?></td>
										<td><?php echo $reg->MSRP?></td>
										<td>
											<img height="100px" src="<?php echo BASE_URL?>producto/getProducto/<?php echo $reg->productCode?>"/>
										</td>
										<td><a
											href="<?php echo BASE_URL?>producto/editProducto/<?php echo $reg->productCode?>"><?php echo _('Editar') ?></a>
											<a
											href="<?php echo BASE_URL?>producto/delProducto/<?php echo $reg->productCode?>"><?php echo _('Eliminar') ?></a>
										</td>
										
									</tr>
									
									<?php endwhile?>
								
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
