
<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <!-- _() es un alias del gettext() -->
                            <?php echo _('Agregar  Juego')?>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <!--<form class="form-signin" action="<?php echo BASE_URL?>usuario/editUser" method="POST">-->
                                    <form role="form" method="POST" id="form_addJuego">

                                        <div class="form-group">
                                            <label><?php echo _('Nombre del Juego')?></label>
                                            <input
                                                    class="form-control" placeholder="Ingrese nombre del juego"
                                                    name="title" id="title">
                                        </div>
                                        <div class="form-group">
                                            <label><?php echo _('Num. Jugadores')?></label>
                                            <input
                                                    class="form-control" placeholder="Ingrese numero de jugadores"
                                                    name="players" id="players">
                                        </div>
                                        <div class="form-group">
                                            <label><?php echo _('Distribuidora')?></label>
                                            <input
                                                    class="form-control" placeholder="Ingrese nombre de distribuidora" name="developer"
                                                    id="developer">
                                        </div>

                                        <div class="form-group">
                                            <label><?php echo _('Genero')?></label>
                                            <input
                                                    class="form-control" placeholder="Ingrese Genero" name="genero"
                                                    id="genero">
                                        </div>
                                        <div class="form-group">
                                            <label><?php echo _('Descripcion')?></label>
                                            <textarea class="form-control"  name="overview" id="overview" cols="30" rows="10" >

                                            </textarea>
                                        </div>

                                        <button type="button" id="btn_registrar" class="btn btn-primary"><?php echo _('Registrar')?></button>

                                        <div id="zona_respuesta"></div>
                                    </form>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end row -->


        </div> <!-- container -->

    </div> <!-- content -->

    <footer class="footer text-right">
        2016 - 2017 © Adminto.
    </footer>

</div>


<!-- ============================================================== -->
<!-- End Right content here -->
<!-- ============================================================== -->







