<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">

            <div class="row">

                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <a href="<?php echo BASE_URL?>juego/addjuego">Nuevo</a>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover table-condensed"
                                       id="dataTables-usuarios">
                                    <thead>
                                    <tr>
                                        <th><?php echo _('Codigo')?></th>
                                        <th><?php echo _('Nombre del Juego')?></th>
                                        <th><?php echo _('Num. J.')?></th>
                                        <th><?php echo _('Distribuidora')?></th>
                                        <th><?php echo _('Genero')?></th>
                                        <th><?php echo _('Descripcion')?></th>
                                        <th><?php echo _('Opciones')?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="body_usuarios">

                                    <?php while($reg = $this->juego->fetch_object()):?>

                                        <tr>
                                            <td><?php echo $reg->id?></td>
                                            <td><?php echo $reg->GameTitle?></td>
                                            <td><?php echo $reg->Players?></td>
                                            <td><?php echo $reg->Developer?></td>
                                            <td><?php echo $reg->Genre?></td>
                                            <td><?php echo $reg->Overview?></td>
                                            <td><a
                                                    href="<?php echo BASE_URL?>juego/editJuego/<?php echo $reg->id?>"> <button class="btn btn-icon waves-effect waves-light btn-success m-b-5"><i class="fa fa-pencil" aria-hidden="true"></i></button></a>
                                                <a
                                                    href="<?php echo BASE_URL?>juego/delJuego/<?php echo $reg->id?>"> <button class="btn btn-icon waves-effect waves-light btn-danger m-b-5"><i class="fa fa-trash-o" aria-hidden="true"></i></button></a>
                                            </td>
                                        </tr>

                                    <?php endwhile?>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <!-- end row -->


        </div> <!-- container -->

    </div> <!-- content -->

    <footer class="footer text-right">
        2016 - 2017 © Adminto.
    </footer>

</div>


<!-- ============================================================== -->
<!-- End Right content here -->
<!-- ============================================================== -->


